### ISSUE TITLE
Open Class Hall Report

### ISSUE THREAD

**Issue by syndenbock** [alarofrunetotem/GarrisonCommander#10]
Currently there is no way to show the class order hall report using the minimap button.
It would be useful to be able to open it using the middle mouse button.

**Comment by alar77** [comment]
If you are in azeroth, it works

**Comment by syndenbock** [comment]
What do you mean by that?
I can open the BfA mission reports with left click, the garrisson report with right click, but I cannot find a button to open the legion mission reports.
