### ISSUE TITLE
Error completing missions in Dalaran with button in GarrisonCommander

### ISSUE THREAD

**Issue by LiquidAtoR** [alarofrunetotem/GarrisonCommander#13]
`Date: 2019-01-30 22:39:21
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\GarrisonCommander\MissionCompletion.lua line 139:
   attempt to index local 'module' (a nil value)
Debug:
   ...rface\AddOns\GarrisonCommander\MissionCompletion.lua:139:
      ...rface\AddOns\GarrisonCommander\MissionCompletion.lua:133
   (tail call): ?
   ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1012:
      ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1012
Locals:
self = <table> {
 OnInitialized = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:401
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMissionResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:310
 EnableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 GetName = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "GarrisonCommander_MissionCompletion"
 IsEnabled = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 CloseReport = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:111
 DisableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 GenerateMissionCompleteList = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:26
 MissionsPrintResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:340
 MissionAutoComplete = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:218
 GetMission = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:205
 IsModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 SetDefaultModuleState = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 SetEnabledState = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 MissionComplete = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:133
 baseName = "GarrisonCommander"
 OnInitialize = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:402
 IterateModules = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 MissionsCleanup = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:82
 Events = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:100
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 moduleName = "MissionCompletion"
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
this = GCQuickHallMissionCompletionButton {
 0 = <userdata>
 tooltip = "Complete all missions without confirmation"
 Left = <unnamed> {
 }
 Text = GCQuickHallMissionCompletionButtonText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 missionType = 4
}
button = "LeftButton"
skiprescheck = false
module = nil
(*temporary) = <table> {
 OnInitialized = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:401
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMissionResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:310
 EnableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  WowheadLooter, v80100
  AddOnSkins, v4.08
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucScanData, v8.0.6150 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BagBrother, v
  BagSync, v11.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  Collectinator, v8.1.0.1
  ElvUI, v10.86
  ElvUICastBarOverlay, v1.07
  ElvUICustomTweaks, v1.38
  ElvUILocPlus, v2.40
  ElvUIMicrobar, v1.85
  ElvUIVisualAuraTimers, v1.56
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  EnhancedPetBattleUI, v2.24
  GarrisonCommander, v3.0.1 70200
  GarrisonCommanderBroker, v3.0.1 1.1.0
  GatherMate2, v1.43.5
  GatherMateSharing, vv1.11
  Informant, v8.0.6159 (SwimmingSeadragon)
  Omen, v3.2.0
  OmniCC, v8.1.1
  Rarity, v1.0 (r682-release)
  RarityOptions, v
  Recount, vv8.1.0c
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TellMeWhen, v8.5.9
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=4d1)

`

**Comment by alar77** [comment]
Is it now possible to manage Garrisons in Dalaran ?!? Ops, I was not aware of it, si it's likely it doesnt work..

**Comment by LiquidAtoR** [comment]
This happened in the Priest's Class Order Hall.
Each class had one in WoD: https://www.wowhead.com/unlocking-and-directions-to-each-order-hall-guide
You have dailies from Garrison, you have dailies from Dalaran Class Order Hall, and now you have dailies in BfA onboard the ship :P 
Three different expansions, three different type of dailies :P

**Comment by LiquidAtoR** [comment]
Druid Class Order Hall same story :)

Date: 2019-03-16 14:27:32
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\GarrisonCommander\MissionCompletion.lua line 139:
   attempt to index local 'module' (a nil value)
Debug:
   ...rface\AddOns\GarrisonCommander\MissionCompletion.lua:139:
      ...rface\AddOns\GarrisonCommander\MissionCompletion.lua:133
   (tail call): ?
   ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1012:
      ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1012
Locals:
self = <table> {
 OnInitialized = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:401
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMissionResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:310
 EnableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 GetName = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "GarrisonCommander_MissionCompletion"
 IsEnabled = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 CloseReport = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:111
 DisableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 GenerateMissionCompleteList = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:26
 MissionsPrintResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:340
 MissionAutoComplete = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:218
 GetMission = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:205
 IsModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 SetDefaultModuleState = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 SetEnabledState = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 MissionComplete = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:133
 baseName = "GarrisonCommander"
 OnInitialize = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:402
 IterateModules = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 MissionsCleanup = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:82
 Events = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:100
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 moduleName = "MissionCompletion"
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
this = GCQuickHallMissionCompletionButton {
 0 = <userdata>
 tooltip = "Complete all missions without confirmation"
 Left = <unnamed> {
 }
 Text = GCQuickHallMissionCompletionButtonText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 missionType = 4
}
button = "LeftButton"
skiprescheck = false
module = nil
(*temporary) = <table> {
 OnInitialized = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\LibInit.lua:401
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMissionResults = <function> defined @Interface\AddOns\GarrisonCommander\MissionCompletion.lua:310
 EnableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  AddOnSkins, v4.10
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  BagSync, v11.1
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Collectinator, v8.1.0.1
  ElvUI, v11.06
  ElvUICastBarOverlay, v1.07
  ElvUICustomTweaks, v1.45
  ElvUILocPlus, v2.41
  ElvUIMicrobar, v1.85
  ElvUIVisualAuraTimers, v1.58
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  EnhancedPetBattleUI, v2.24
  GarrisonCommander, v3.0.2 70200
  GarrisonCommanderBroker, v3.0.2 1.1.0
  GatherMate2, v1.43.6
  GatherMateSharing, vv1.11
  Informant, v8.1.6246 (SwimmingSeadragon)
  Omen, v3.2.0
  OmniCC, v8.1.1
  Rarity, v1.0 (r686-release)
  RarityOptions, v
  Recount, vv8.1.0d
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TellMeWhen, v8.6.0
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=4d1)

**Comment by alar77** [comment]
Order Hall were born in Legion AFAIK.
If you are using Garrison Commander to manage order hall missions, you are using the wrong addon. The order hall missions addon is OrderHallCommander. Maybe some limited support for them was left in GarrisonCommander but I clearly state I was not supporting it.
If instead you are managing Garrison Missions please help me in finding where they can be managed when in order hall. I could not fond a way

**Comment by LiquidAtoR** [comment]
No, it's the Order Hall Missions I was talking about.
When I open the order hall missions table, Garrison Commander pops up here, whether it's supported or not.
Perhaps then disable GC when you are doing the order hall things?

**Comment by alar77** [comment]
I just released (thanks to wildcard_25) a release wherer any reference to Order Hall Missions should have been removed.
Could you check?
Also, I could not replicate the issue with my toons

**Comment by LiquidAtoR** [comment]
I'm currently 3 weeks at work so unlikely will have a chance to check
before that time.
In the event I can, will let you know my findings.

Cheers, Mike.

Op vr 29 mrt. 2019 21:40 schreef Giovanni G <notifications@github.com>:

**Comment by alar77** [comment]
Assuming fix worked
