### ISSUE TITLE
MissionControl.lua:402: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"

### ISSUE THREAD

**Issue by Thrumbar** [alarofrunetotem/GarrisonCommander#15]
1x GarrisonCommander\MissionControl.lua:402: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
[C]: in function `CreateFrame'
GarrisonCommander\MissionControl.lua:402: in function <GarrisonCommander\MissionControl.lua:389>
GarrisonCommander\MissionControl.lua:842: in function `BuildRewards'
GarrisonCommander\MissionControl.lua:582: in function <GarrisonCommander\MissionControl.lua:560>
(tail call): ?
[C]: ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:498: in function `InitializeAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:613: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:636: in function `Garrison_LoadUI'
FrameXML\UIParent.lua:1734: in function <FrameXML\UIParent.lua:1090>
[C]: ?

**Comment by alar77** [comment]
see #17
