### ISSUE TITLE
Issues with the Mission Control Screen after 8.1.5

### ISSUE THREAD

**Issue by missebet** [alarofrunetotem/GarrisonCommander#17]
Please see attached screenshots, one with ElvUi on and one with ElvUi off.

LUA Error#1 
Message: ...nterface\AddOns\GarrisonCommander\MissionControl.lua:402: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
Time: Tue Mar 12 18:01:02 2019
Count: 1
Stack: ...nterface\AddOns\GarrisonCommander\MissionControl.lua:402: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
[C]: in function `CreateFrame'
...nterface\AddOns\GarrisonCommander\MissionControl.lua:402: in function <...nterface\AddOns\GarrisonCommander\MissionControl.lua:389>
...nterface\AddOns\GarrisonCommander\MissionControl.lua:842: in function `BuildRewards'
...nterface\AddOns\GarrisonCommander\MissionControl.lua:582: in function <...nterface\AddOns\GarrisonCommander\MissionControl.lua:560>
(tail call): ?
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:636: in function `Garrison_LoadUI'
Interface\FrameXML\UIParent.lua:1982: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

Error#2 
Message: Interface\AddOns\GarrisonCommander\ShipControl.lua:456: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
Time: Tue Mar 12 18:01:02 2019
Count: 1
Stack: Interface\AddOns\GarrisonCommander\ShipControl.lua:456: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
[C]: in function `CreateFrame'
Interface\AddOns\GarrisonCommander\ShipControl.lua:456: in function <Interface\AddOns\GarrisonCommander\ShipControl.lua:442>
Interface\AddOns\GarrisonCommander\ShipControl.lua:850: in function `BuildRewards'
Interface\AddOns\GarrisonCommander\ShipControl.lua:636: in function <Interface\AddOns\GarrisonCommander\ShipControl.lua:614>
(tail call): ?
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...nder\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:636: in function `Garrison_LoadUI'
Interface\FrameXML\UIParent.lua:1982: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

Error#3
Message: ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:2367: attempt to index field 'startButton' (a nil value)
Time: Tue Mar 12 18:01:05 2019
Count: 1
Stack: ...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:2367: attempt to index field 'startButton' (a nil value)
...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:2367: in function `OpenMissionControlTab'
...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1548: in function <...rface\AddOns\GarrisonCommander\GarrisonCommander.lua:1548>

Locals: self = <table> {
 IsFollowerUpgrade = <function> defined @Interface\AddOns\GarrisonCommander\Init.lua:241
 ScriptGarrisonMissionFrame_OnShow = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1723
 ApplyMINXPLEVEL = <function> defined @Interface\AddOns\GarrisonCommander\MissionControl.lua:768
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\Ace3\AceTimer-3.0\AceTimer-3.0.lua:145
 OpenFollowersTab = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:2347
 ApplyMAXRES = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:552
 HookedGarrisonFollowerListButton_OnClick = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1341
 ApplyIXP = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:615
 GarrisonMissionFrame_SelectTab = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:3139
 DrawSingleButton = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:2776
 AddFollowersToButton = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:3067
 TestMissionExtra = <function> defined @Interface\AddOns\GarrisonCommander\MissionCache.lua:485
 EventGARRISON_MISSION_STARTED = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:957
 ScheduleTimer = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\Ace3\AceTimer-3.0\AceTimer-3.0.lua:92
 ApplySGCSKIPEPIC = <function> defined @Interface\AddOns\GarrisonCommander\ShipControl.lua:774
 GetMarketValue = <function> defined @Interface\AddOns\GarrisonCommander\MissionCache.lua:81
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 MCMatchMaker = <function> defined @Interface\AddOns\GarrisonCommander\MatchMaker.lua:349
 OpenProgressTab = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:2355
 showdata = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:519
 CleanUp = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1914
 ApplyGCSKIPRARE = <function> defined @Interface\AddOns\GarrisonCommander\MissionControl.lua:764
 CreatePrivateDb = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:884
 ApplyFOLLOWERMISSIONLIST = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:610
 AddOptionToOptionsLayer = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1099
 Garrison_SortMissions_Class = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:361
 UnregisterAllEvents = <function> defined @Interface\AddOns\GarrisonCommander\libs\LibInit\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 IsFollowerList = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1271
 RaiseCompleteDialog = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1768
 ApplyBIGSCREEN = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:576
 shipyardDone = <function> defined @Interface\AddOns\GarrisonCommander\quick.lua:28
 IsProgressMissionPage = <function> defined @Interface\AddOns\GarrisonCommander\GarrisonCommander.lua:1265
 revision = "868da2e"
 GetName = <function> defined @Int

![WoWScrnShot_031219_160428](https://user-images.githubusercontent.com/23659348/54236164-f6790480-44e0-11e9-95af-236b065878b3.jpg)
![WoWScrnShot_031219_155943](https://user-images.githubusercontent.com/23659348/54236165-f6790480-44e0-11e9-99af-3411cad62a98.jpg)

**Comment by alar77** [comment]
I am not able to launch wow due to Wine issue, but I saw that blizzard removed ItemButtonTemplate and now there only is ItemButton wich is no longer virtual. Changing reference and uploading a beta.Can anyone test it?

**Comment by Ludovicus-Maior** [comment]
I'll give it a test as soon as I see it.

**Comment by Ludovicus-Maior** [comment]
AOK.  Now downloading 3.0.1.Beta1

**Comment by JimGiordano2** [comment]
Just tried beta.  Very little changed if anything.

**Comment by Ludovicus-Maior** [comment]
I think the fix needs to be:
```
row= CreateFrame('ItemButton', "Priority" .. frameIndex, frame)
```
ItemButton is now a UI element, not a template.
Tested on the regular command table and shipyard.

**Comment by alar77** [comment]
AHA, this makes absolutely sense. I looked around for UI patch notes but could not find them. Cooking a beta2

**Comment by alar77** [comment]
Out 3.0.2.Beta2

**Comment by Ludovicus-Maior** [comment]
Cool.  Will test within the hour.   I'm technically at work :-).

**Comment by JimGiordano2** [comment]
That seems to have worked!   :)

**Comment by Ludovicus-Maior** [comment]
Agreed!  Looks good.
Both command tables now work.

**Comment by alar77** [comment]
So many thanks guys, tagging it as official release!

**Comment by missebet** [comment]
TY for fixing this! Hugs to all you folks working on it.
