### ISSUE TITLE
Error with strings

### ISSUE THREAD

**Issue by Galaxy-Wizard** [alarofrunetotem/GarrisonCommander#23]
Take a look here:

https://ibb.co/xMwQL1Q

The starting letters of translation are missed in red selected places.
The error source is wrong usage of special string tokens: first letters are missed.

Something like this is in code: %%s instead of %s.

Could you find the errors?

**Comment by alar77** [comment]
Are you saying that I have %%s somewhere?

**Comment by alar77** [comment]
Btw, I had a look at russian localization, and the nice guy who translated to russian made a mess with %1$d stuff... I'll try to fix it and will see if things improve.
Otherwise tou can directly check localization on curseforge

**Comment by alar77** [comment]
Closing, because there is no way I can fix russian localization :( Every one wanting to fix localization on curse is welcome
