### ISSUE TITLE
Broken with patch 8.2

### ISSUE THREAD

**Issue by KharnosStrayder** [alarofrunetotem/GarrisonCommander#25]
The new patch has broken the addon again.

When I try and move the commander window like I had without issue in times past the entire garrison window locks up and freezes causing me to have to /reload ui to fix it.

I've attached a screenshot
![World of Warcraft 2019_06_27 10_37_37](https://user-images.githubusercontent.com/12408363/60225244-4bdaf500-98c9-11e9-8cc6-9c8a09c6d76d.png)

**Comment by alar77** [comment]
I released a new version on july the first and it's working afaik
