### ISSUE TITLE
Interface action failed because of an AddOn

### ISSUE THREAD

**Issue by Neurotoxin001** [alarofrunetotem/GarrisonCommander#26]
After 8.2 patch I got:
`Interface action failed because of an AddOn`
When open missions report menu when in combat. Disabling `GarrisonCommander` is resolves that issue, all other addons is fine.

No lua errors btw.

I have 3.1.1 version.

**Comment by Neurotoxin001** [comment]
Still not fixed in 3.2.0.

**Comment by alar77** [comment]
Hunting taint issues is very hard and, honestly, I dont feel that GarrisonCommander is intended to be used while fighting, nevertheless I could use some more info, like
How did you open mission report? AFAIK the button on minimap opens mission report from the very last garrison like setting (Champions,righe now).

**Comment by Neurotoxin001** [comment]
Right click on minimap button.

**Comment by alar77** [comment]
if by "fix it" you mean that the report still cant be open but no longer an error message appear, then the fix is on the way :)

**Comment by Neurotoxin001** [comment]
That's will be crutch, not a fix.

**Comment by alar77** [comment]
Man, it's Blizzard. Addons are not allowed to do everything Blizzard code can do.
When in combat I cant inteerfere with blizzard things, so while in combat you can only see the current zone report

**Comment by Neurotoxin001** [comment]
Now it's doesn't open even out of combat.

**Comment by alar77** [comment]
Feature has been (maybe temporary) removed from Garrison Commander. You need to enable Garrison Commander Broker (which is bundled with Garrison Commander)  to have it
