### ISSUE TITLE
Garrison Commander UI has a Glitch

### ISSUE THREAD

**Issue by GnuclearGnome** [alarofrunetotem/GarrisonCommander#27]
I have the option Unlock Panel checked.  This ability was one of the main reasons I initially downloaded GarrisonCommander way back in early WoD.  Anyway, with the latest version of GarrisonCommander (v3.2.1) installed, when I try to move the Mission screen by clicking on the top of the frame, as soon as I move my mouse to try and move the frame, the Mission Table UI becomes unresponsive.  Everything behind the UI now appears to be "in play" as in the tool tips for all objects and NPCs show up and the cursor changes based not on the Mission Table UI, but on what background object is being cursored over.  If you close the Mission Table and reopen it, it comes up blank.  Also, if you have the options at the top of the frame open, as soon as you try to move the frame the options portion blanks out immediately except for the checkmarks and other elements of the options UI (Sort Missions By dropdown and Minimum needed chance slider bar, etc.).  Doing a /reload brings everything back to normal.

I have BugGrabber and BugSack installed and no errors of any kind are being reported when this happens.  Also, I verified that this occurs with nothing loaded except GarrisonCommander and BugGrabber/BugSack.

This could have been present in earlier versions, I haven't tried what I described for quite a while. 
![GC Error](https://user-images.githubusercontent.com/42303532/62086868-bdda8d00-b22d-11e9-80b5-1f138895be1c.jpg)

 
![GC Error 2](https://user-images.githubusercontent.com/42303532/62086972-14e06200-b22e-11e9-9dde-7ede3743024c.jpg)

**Comment by GnuclearGnome** [comment]
Might this be related to the changes Blizz made to the Frame Anchoring code in 8.2, perhaps?

**Comment by alar77** [comment]
Why cant they leave things alone? :) Hunting it down

**Comment by alar77** [comment]
I had to disable unlock Panel, sorry guys
