### ISSUE TITLE
championcommander, garrisoncommander, and orderhallcommander are not working as of prepatch for shadowlands

### ISSUE THREAD

**Issue by jamesevarts3** [alarofrunetotem/GarrisonCommander#34]
championcommander, garrisoncommander, and orderhallcommander are not working as of prepatch for shadowlands

**Comment by Kirbdawg** [comment]
Please.   I logon to 28 characters a day just to do the Garrison mission table on each for easy gold making.   Without this one in particular, it would take hours to go through them all.  Can't live without you! hehe
