### ISSUE TITLE
Shipyard "Open Garrison Commander Mission Control" Bugged

### ISSUE THREAD

**Issue by coldwinter18** [alarofrunetotem/GarrisonCommander#47]
That option is bugged for sooooooooooooooooooo long. While the other one with the followers is working fine and I am using it to send multiple missions automatically, on the shipyard is not working... sometimes even the UI bugs and shows me, followers from my garrison and not ships...

**Comment by alar77** [comment]
I never had this bug, but I only open Shipyard from the second tablei in the garrison main hall.
Are you using the one at the actual shipyard?

**Comment by missebet** [comment]
I have issue's no matter which table I use.  It really bugs out when changing ship equipment, randomly throwing the error that I have to disable addons due to the process being blocked by the blizzard API
