### ISSUE TITLE
Broken with Pre-Patch for Dragonflight

### ISSUE THREAD

**Issue by nevermiii** [alarofrunetotem/GarrisonCommander#50]
Broken with Pre-Patch for Dragonflight

**Comment by Sinutok** [comment]
Yes, didnt work in any way

**Comment by gawlow** [comment]
Unfortunately, Blizzard had changed the whole Garrison API, so the addon would need a big overhaul. The data structure for some of the objects has changed too. Too bad as this addon was one of the best for Draenor Garrison

**Comment by Caerdon** [comment]
I'm taking a look.  I just pushed up a pull request to fix ChampionCommander.  I'm expecting the changes will be similar here.

**Comment by Caerdon** [comment]
Here's the pull request that gets things working: https://github.com/alarofrunetotem/GarrisonCommander/pull/52
