### ISSUE TITLE
Updates for Dragonflight

### ISSUE THREAD

**Issue by Nancara** [alarofrunetotem/GarrisonCommander#51]
Are you planning to update your add-ons for the Dragonflight? I have been using the table add-ons since WoD and like them. A friend recommended your fishing add-on. But there are a lot of Lua issues with them. Thanks for creating the add-ons I hope there are updates in the works.

**Comment by Caerdon** [comment]
I have a pull request out that gets things largely working: https://github.com/alarofrunetotem/GarrisonCommander/pull/52
