### ISSUE TITLE
LUA error at BFA Missions

### ISSUE THREAD

**Issue by Scaver** [alarofrunetotem/GarrisonCommander#6]
```
5x ...rfaceGarrisonCommander\GarrisonCommander-2.18.8 70200.lua:3158: attempt to index local 'module' (a nil value)
...rfaceGarrisonCommander\GarrisonCommander-2.18.8 70200.lua:3158: in function <...rfaceGarrisonCommander\GarrisonCommander.lua:3154>
(tail call): ?
[C]: in function `GarrisonMissionButton_SetRewards'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:984: in function `Update'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:891: in function `UpdateMissions'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:429: in function `UpdateMissions'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:95: in function `OnEventMainFrame'
Blizzard_GarrisonUI\Blizzard_BFAMissionUI.lua:264: in function <Blizzard_GarrisonUI\Blizzard_BFAMissionUI.lua:260>

Locals:
self = <table> {
 IsFollowerUpgrade = <function> defined @GarrisonCommander\Init.lua:241
 ScriptGarrisonMissionFrame_OnShow = <function> defined @GarrisonCommander\GarrisonCommander.lua:1722
 ApplyMINXPLEVEL = <function> defined @GarrisonCommander\MissionControl.lua:768
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:147
 OpenFollowersTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:2346
 ApplyMAXRES = <function> defined @GarrisonCommander\GarrisonCommander.lua:551
 HookedGarrisonFollowerListButton_OnClick = <function> defined @GarrisonCommander\GarrisonCommander.lua:1340
 ApplyIXP = <function> defined @GarrisonCommander\GarrisonCommander.lua:614
 GarrisonMissionFrame_SelectTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:3138
 DrawSingleButton = <function> defined @GarrisonCommander\GarrisonCommander.lua:2775
 AddFollowersToButton = <function> defined @GarrisonCommander\GarrisonCommander.lua:3066
 TestMissionExtra = <function> defined @GarrisonCommander\MissionCache.lua:485
 EventGARRISON_MISSION_STARTED = <function> defined @GarrisonCommander\GarrisonCommander.lua:956
 ScheduleTimer = <function> defined @ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:94
 ApplySGCSKIPEPIC = <function> defined @GarrisonCommander\ShipControl.lua:774
 GetMarketValue = <function> defined @GarrisonCommander\MissionCache.lua:81
 db = <table> {
 }
 SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 MCMatchMaker = <function> defined @GarrisonCommander\MatchMaker.lua:349
 OpenProgressTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:2354
 showdata = <function> defined @GarrisonCommander\GarrisonCommander.lua:518
 CleanUp = <function> defined @GarrisonCommander\GarrisonCommander.lua:1913
 ApplyGCSKIPRARE = <function> defined @GarrisonCommander\MissionControl.lua:764
 CreatePrivateDb = <function> defined @GarrisonCommander\GarrisonCommander.lua:883
 ApplyFOLLOWERMISSIONLIST = <function> defined @GarrisonCommander\GarrisonCommander.lua:609
 AddOptionToOptionsLayer = <function> defined @GarrisonCommander\GarrisonCommander.lua:1098
 Garrison_SortMissions_Class = <function> defined @GarrisonCommander\GarrisonCommander.lua:361
 UnregisterAllEvents = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 IsFollowerList = <function> defined @GarrisonCommander\GarrisonCommander.lua:1270
 RaiseCompleteDialog = <function> defined @GarrisonCommander\GarrisonCommander.lua:1767
 ApplyBIGSCREEN = <function> defined @GarrisonCommander\GarrisonCommander.lua:575
 shipyardDone = <function> defined @GarrisonCommander\quick.lua:28
 IsProgressMissionPage = <function> defined @GarrisonCommander\GarrisonCommander.lua:1264
 revision = "04a2710"
 GetName = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetHeroesIterator = <function> defined @GarrisonCommander\FollowerCache.lua:271
 name = "GarrisonCommander"
 GetBiasColor = <function> defined @GarrisonCommander\GarrisonCommander.lua:2073
 Disable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 AddIconsToFollower = <function> defined @GarrisonCommander\GarrisonCommander.lua:685
 OnAllGarrisonMissions = <function> defined @GarrisonCommander\MissionCache.lua:366
 Unhook = <function> defined @ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Int
```

**Comment by sgkdnay** [comment]
same thing: 

26x ...rfaceGarrisonCommander\GarrisonCommander-2.18.8 70200.lua:3158: attempt to index local 'module' (a nil value)
...rfaceGarrisonCommander\GarrisonCommander-2.18.8 70200.lua:3158: in function <...rfaceGarrisonCommander\GarrisonCommander.lua:3154>
(tail call): ?
[C]: in function `GarrisonMissionButton_SetRewards'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:984: in function `Update'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:891: in function `UpdateMissions'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:429: in function `UpdateMissions'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:857: in function `GarrisonMissionListTab_SetTab'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:843: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:841>

Locals:
self = <table> {
 IsFollowerUpgrade = <function> defined @GarrisonCommander\Init.lua:241
 ScriptGarrisonMissionFrame_OnShow = <function> defined @GarrisonCommander\GarrisonCommander.lua:1722
 ApplyMINXPLEVEL = <function> defined @GarrisonCommander\MissionControl.lua:768
 modules = <table> {
 }
 CancelTimer = <function> defined @DialogKey\libs\AceTimer-3.0\AceTimer-3.0.lua:145
 OpenFollowersTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:2346
 ApplyMAXRES = <function> defined @GarrisonCommander\GarrisonCommander.lua:551
 HookedGarrisonFollowerListButton_OnClick = <function> defined @GarrisonCommander\GarrisonCommander.lua:1340
 ApplyIXP = <function> defined @GarrisonCommander\GarrisonCommander.lua:614
 GarrisonMissionFrame_SelectTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:3138
 DrawSingleButton = <function> defined @GarrisonCommander\GarrisonCommander.lua:2775
 AddFollowersToButton = <function> defined @GarrisonCommander\GarrisonCommander.lua:3066
 TestMissionExtra = <function> defined @GarrisonCommander\MissionCache.lua:485
 EventGARRISON_MISSION_STARTED = <function> defined @GarrisonCommander\GarrisonCommander.lua:956
 ScheduleTimer = <function> defined @DialogKey\libs\AceTimer-3.0\AceTimer-3.0.lua:92
 ApplySGCSKIPEPIC = <function> defined @GarrisonCommander\ShipControl.lua:774
 GetMarketValue = <function> defined @GarrisonCommander\MissionCache.lua:81
 db = <table> {
 }
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 MCMatchMaker = <function> defined @GarrisonCommander\MatchMaker.lua:349
 OpenProgressTab = <function> defined @GarrisonCommander\GarrisonCommander.lua:2354
 showdata = <function> defined @GarrisonCommander\GarrisonCommander.lua:518
 CleanUp = <function> defined @GarrisonCommander\GarrisonCommander.lua:1913
 ApplyGCSKIPRARE = <function> defined @GarrisonCommander\MissionControl.lua:764
 CreatePrivateDb = <function> defined @GarrisonCommander\GarrisonCommander.lua:883
 ApplyFOLLOWERMISSIONLIST = <function> defined @GarrisonCommander\GarrisonCommander.lua:609
 AddOptionToOptionsLayer = <function> defined @GarrisonCommander\GarrisonCommander.lua:1098
 Garrison_SortMissions_Class = <function> defined @GarrisonCommander\GarrisonCommander.lua:361
 UnregisterAllEvents = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 IsFollowerList = <function> defined @GarrisonCommander\GarrisonCommander.lua:1270
 RaiseCompleteDialog = <function> defined @GarrisonCommander\GarrisonCommander.lua:1767
 ApplyBIGSCREEN = <function> defined @GarrisonCommander\GarrisonCommander.lua:575
 shipyardDone = <function> defined @GarrisonCommander\quick.lua:28
 IsProgressMissionPage = <function> defined @GarrisonCommander\GarrisonCommander.lua:1264
 revision = "04a2710"
 GetName = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GetHeroesIterator = <function> defined @GarrisonCommander\FollowerCache.lua:271
 name = "GarrisonCommander"
 GetBiasColor = <function> defined @GarrisonCommander\GarrisonCommander.lua:2073
 Disable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 AddIconsToFollower = <function> defined @GarrisonCommander\GarrisonCommander.lua:685
 OnAllGarrisonMissions = <function> defined @GarrisonCommander\MissionCache.lua:366
 Unhook = <function> defined @Titan\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <fu
