### ISSUE TITLE
Mostly cosmetic fixes

### ISSUE THREAD

**Issue by WildCard-25** [alarofrunetotem/GarrisonCommander#8]
[gc.zip](https://github.com/alarofrunetotem/GarrisonCommander/files/2299118/gc.zip)
The patch doesn't format as code properly so I'll try to go through each block of changes descriptively :-)

- FollowerPage.lua
  - Allow armor and weapon upgrades to be applied to inactive followers
  - Fix blizzard visual bug that overlaps the follower acquisition text and armor/weapon pLevels for uncollected followers
- GarrisonCommander.lua
  - Fix hiding of corner textures for option frame
  - (1/2) Change armor pLevel/weapon pLevel/xp placement so they are always inside the button they belong to. This may conflict with Master Plan's placement of the same, but as these can be turned off in either addon, this shouldn't be a problem
  - Use existing boolean for test
  - (2/2) Change armor pLevel/weapon pLevel/xp placement part 2
  - fix upgrades still showing when moving from a follower that has an upgrade available to an uncollected follower
  - fix last follower mission list button sometimes being about half the size of the rest by setting the button to fullwidth before attaching it to the list
- GarrisonCommander.xml
  - fix lua error when clicking on one of the traits in the trait filter
- MissionControl.lua
  - fix last mission button sometimes being too wide by setting the button to fullwidth before attaching it to the list
- ShipControl.lua
  - fix last ship mission button sometimes being too wide by setting the button to fullwidth before attaching it to the list
- ShipYard.lua
  - change location of mission success percentage so that it doesn't stick out of the side of the map for some missions
  - fix Mission Control tab so that it doesn't move and overlap the Help tab when opening and closing the options panel
  - fix Quickrun tab so that it doesn't move when opening and closing the option panel

**Comment by WildCard-25** [comment]
All changes in patch still valid for v3.0.0. Patch still applies without conflict.

**Comment by alar77** [comment]
Hi mate, if you could fork the code, apply the patch and open a pull request, I woul really happy to include it

**Comment by WildCard-25** [comment]
Done :-)

**Comment by alar77** [comment]
Thanks!! Will review it during the weekend

**Comment by alar77** [comment]
Pushed as 3.1.0.
Many thanks
